default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: schoolReview_dev

test: &test
  <<: *default
  database: schoolReview_test
