development:
  adapter: postgresql
  database: schoolReview_dev
  encoding: unicode
  pool: 5
  username: root
  password: bharatha
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: schoolReview_test
  encoding: unicode
  pool: 5
  username: root
  password: bharatha
  host: localhost
  port: 5432

production:
  adapter: postgresql
  database: schoolReview_prod
  encoding: unicode
  pool: 5
  username: root
  password: bharatha
  host: localhost
  port: 5432