development:
  adapter: sqlite3
  encoding: unicode
  database: schoolReview_development
  host: localhost
  pool: 5
  username: root
  password: bharatha
  timeout: 5000

test:
  adapter: sqlite3
  encoding: unicode
  database: schoolReview_test
  host: localhost
  pool: 5
  username: root
  password: bharatha
  timeout: 5000

production:
  adapter: sqlite3
  encoding: unicode
  database: schoolReview_production
  host: localhost
  pool: 5
  username: root
  password: bharatha
  timeout: 5000
